### ISSUE TITLE
Unit testing TwinCAT C#

### ISSUE THREAD

**Issue by runtimevic** [densogiaichned/TcCppTest#1]
Hello @densogiaichned ,
Do you know any example of how I could perform unit tests for TwinCAT in C#??
and also a TwinCAT method with: {attribute 'TcRpcEnable'} , RPC (remote procedure call) that is called asynchronously from C# as a unit test?
Thanks for everything, Victor.

**Comment by densogiaichned** [comment]
Hi @runtimevic,
do you mean unit tests for ADS calls in C#? 
Regards

**Comment by runtimevic** [comment]
> 



> Hi @runtimevic, do you mean unit tests for ADS calls in C#? Regards

Hello @densogiaichned ,
you have in TwinCAT a method which has enabled  {attribute 'TcRpcEnable'} , RPC (remote procedure call), I would like to be able to perform unit tests of these methods from C #....
Regards, Víctor.

**Comment by densogiaichned** [comment]
Something like this ?
```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TwinCAT.Ads;

namespace TestRpcProject
{
    [TestClass]
    public class UnitTestRpc
    {
        [TestMethod]
        public void TestRPC()
        {
            using (TwinCAT.Ads.AdsClient client = new AdsClient())
            {
                client.Connect(851);

                // Call a Method that has the following signature (within MAIN Program)
                /*  {attribute 'TcRpcEnable'}
                    METHOD PUBLIC M_Add : INT
                    VAR_INPUT
                    i1 : INT := 0;
                    i2 : INT := 0;
                    END_VAR 
                */

                short result = (short)client.InvokeRpcMethod("MAIN.fbRPC", "M_Add", new object[] { (short)1, (short)4 });
                Assert.AreEqual(5, result);
            }
        }
    }
}
```

**Comment by runtimevic** [comment]
> Algo como esto ?
> 
> ```cs
> using Microsoft.VisualStudio.TestTools.UnitTesting;
> using TwinCAT.Ads;
> 
> namespace TestRpcProject
> {
>     [TestClass]
>     public class UnitTestRpc
>     {
>         [TestMethod]
>         public void TestRPC()
>         {
>             using (TwinCAT.Ads.AdsClient client = new AdsClient())
>             {
>                 client.Connect(851);
> 
>                 // Call a Method that has the following signature (within MAIN Program)
>                 /*  {attribute 'TcRpcEnable'}
>                     METHOD PUBLIC M_Add : INT
>                     VAR_INPUT
>                     i1 : INT := 0;
>                     i2 : INT := 0;
>                     END_VAR 
>                 */
> 
>                 short result = (short)client.InvokeRpcMethod("MAIN.fbRPC", "M_Add", new object[] { (short)1, (short)4 });
>                 Assert.AreEqual(5, result);
>             }
>         }
>     }
> }
> ```

Hello @densogiaichned , thank you very much to start it is very good for me...
I found this in case you want to look at it and it works for you:
https://github.com/TcOpenGroup/tc.prober
thanks, Víctor.

**Comment by runtimevic** [comment]
> Algo como esto ?
> 
> ```cs
> using Microsoft.VisualStudio.TestTools.UnitTesting;
> using TwinCAT.Ads;
> 
> namespace TestRpcProject
> {
>     [TestClass]
>     public class UnitTestRpc
>     {
>         [TestMethod]
>         public void TestRPC()
>         {
>             using (TwinCAT.Ads.AdsClient client = new AdsClient())
>             {
>                 client.Connect(851);
> 
>                 // Call a Method that has the following signature (within MAIN Program)
>                 /*  {attribute 'TcRpcEnable'}
>                     METHOD PUBLIC M_Add : INT
>                     VAR_INPUT
>                     i1 : INT := 0;
>                     i2 : INT := 0;
>                     END_VAR 
>                 */
> 
>                 short result = (short)client.InvokeRpcMethod("MAIN.fbRPC", "M_Add", new object[] { (short)1, (short)4 });
>                 Assert.AreEqual(5, result);
>             }
>         }
>     }
> }
> ```

hello @densogiaichned , 
I can't get it with numbers of type LREAL or REAL, can you help me?, how would it be?
I put a link for the equivalence between data types:
https://infosys.beckhoff.com/english.php?content=../content/1033/tcsystemmanager/basics/TcSysMgr_DatatypeComparison.htm&id=
thanks....
